Repository Gosrock/Ticket-Admin-22nd, pull requests merged in 2022-08, with the labels that each got.

#8 [유저리스트] 유저 조회 기본 기능 추가
  package-lock.json
  src/apis/users/UsersApi.js
  src/components/Tables/UsersPage/Table.js
  src/components/Tables/UsersPage/UserSearch.js
  src/components/Tables/UsersPage/UsersPage.js
  src/state/action-types/index.js
  src/state/action-types/usersPage.js
  src/state/actions-creators/usersPage.js
  src/state/reducers/index.js
  src/state/reducers/usersPage.js
Labels: For: Views, For: Markup/UX, Type: Feature

#9 [v0.0.4] 유저 조회 기본기능 배포
  .gitignore
  package-lock.json
  src/apis/users/UsersApi.js
  src/components/Tables/OrdersPage/OrdersPage.js
  src/components/Tables/TicketsPage/TicketsPage.js
  src/components/Tables/UsersPage/Table.js
  src/components/Tables/UsersPage/UserSearch.js
  src/components/Tables/UsersPage/UsersPage.js
  src/hoc/AuthPass.js
  src/state/action-types/index.js
  src/state/action-types/usersPage.js
  src/state/actions-creators/logout.js
  src/state/actions-creators/usersPage.js
  src/state/reducers/index.js
  src/state/reducers/usersPage.js
Labels: For: Deploy, For: Views, Type: Feature

#14 :hammer: fix: 검색 옵션만 바뀐 경우에도 검색되도록 수정 #4
  src/components/Tables/UsersPage/UserSearch.js
Labels: For: Views, Type: Refactor

#22 :rocket: feat(CheckPage)
  src/components/Tickets/CheckPage/CheckPage.js
Labels: For: Views, Type: Feature

#26 :hammer: fix(checkpage) : 카메라 전체화면 구동
  package-lock.json
  src/components/Tickets/CheckPage/CheckPage.js
  src/components/Tickets/CheckPage/scanner.svg
  src/components/Tickets/CheckPage/video.css
Labels: For: Markup/UX, Type: Refactor

#27 [v0.1.3] 티켓검사페이지 카메라 전체화면 구동
  package-lock.json
  src/components/Tickets/CheckPage/CheckPage.js
  src/components/Tickets/CheckPage/scanner.svg
  src/components/Tickets/CheckPage/video.css
Labels: For: Deploy, For: Markup/UX, Type: Refactor

#31 [유저리스트] 검색 완료 메시지, 총 유저 수, 관리자 색상 #30
  src/components/Tables/UsersPage/Table.js
  src/components/Tables/UsersPage/UserSearch.js
Labels: For: Views, For: Markup/UX, Type: Feature

#33 Feature/OrdersPage 완성
  src/components/Tables/OrdersPage/OrdersPage.js
  src/components/Tickets/CheckPage/CheckPage.js
  src/state/action-types/index.js
  src/state/action-types/orderListPagination.js
  src/state/actions-creators/CheckPage.js
  src/state/actions-creators/index.js
  src/state/actions-creators/orderListPagination.js
  src/state/reducers/CheckPage.js
  src/state/reducers/index.js
  src/state/reducers/orderListPagination.js
Labels: For: Views, Type: Feature

#35 예시페이지네이션 삭제, 어세스토큰 로그아웃 버그 수정, 댓글 추첨 페이지 분리
  src/components/CommentRandomPage/CommentRandomPage.js
  src/components/LandingPage/LandingPage.js
  src/components/MainLayout/MainLayout.js
  src/components/Tables/ExamplePage/ExamplePage.js
  src/components/Tables/ExamplePage/Table.js
  src/hoc/AuthPass.js
  src/state/actions-creators/slackValidation.js
Labels: For: Views, For: Markup/UX, Type: Refactor

#37 [v0.1.4] 카메라입장페이지,댓글렌덤추첨 페이지추가
  package-lock.json
  src/App.js
  src/components/CommentRandomPage/CommentRandomPage.js
  src/components/LandingPage/LandingPage.js
  src/components/MainLayout/MainLayout.js
  src/components/Tables/ExamplePage/ExamplePage.js
  src/components/Tables/ExamplePage/Table.js
  src/components/Tables/OrdersPage/OrdersPage.js
  src/components/Tables/TicketsPage/TicketsPage.js
  src/components/Tables/UsersPage/Table.js
  src/components/Tables/UsersPage/UserSearch.js
  src/components/Tickets/CheckPage/CheckEnterPage.js
  src/components/Tickets/CheckPage/CheckPage.js
  src/hoc/AuthPass.js
  src/state/action-types/index.js
  src/state/action-types/orderListPagination.js
  src/state/action-types/randomCom.js
  src/state/actions-creators/CheckPage.js
  src/state/actions-creators/index.js
  src/state/actions-creators/orderListPagination.js
  src/state/actions-creators/randomCom.js
  src/state/actions-creators/slackValidation.js
  src/state/actions-creators/ticketPagination.js
  src/state/reducers/CheckPage.js
  src/state/reducers/index.js
  src/state/reducers/orderListPagination.js
  src/state/reducers/randomCom.js
Labels: For: Deploy, Type: Feature

#38 [v0.1.4] 파일명 대소문자 오류 재배포
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/state/action-types/checkPage.js
Labels: For: Deploy, Type: Refactor

#39 [v0.1.4] public 파일추가.. 재배포
  .gitignore
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
Labels: For: Deploy, Type: Refactor

#40 :hammer:fix:유저 아이디 추가
  src/components/CommentRandomPage/CommentRandomPage.js
  src/state/actions-creators/randomCom.js
Labels: For: Views, For: Markup/UX, Type: Feature

#41 Feature/CheckPage 기능 구현 완료
  src/components/Tables/OrdersPage/OrdersPage.js
  src/components/Tickets/CheckPage/CheckEnterPage.js
  src/components/Tickets/CheckPage/CheckPage.js
  src/state/action-types/checkPage.js
  src/state/actions-creators/CheckPage.js
  src/state/reducers/CheckPage.js
Labels: For: Views, Type: Feature

#43 [v0.1.5] 큐알 중복요청 방지 기능 개선
  src/components/CommentRandomPage/CommentRandomPage.js
  src/components/Tables/OrdersPage/OrdersPage.js
  src/components/Tickets/CheckPage/CheckEnterPage.js
  src/components/Tickets/CheckPage/CheckPage.js
  src/state/action-types/checkPage.js
  src/state/actions-creators/CheckPage.js
  src/state/actions-creators/randomCom.js
  src/state/reducers/CheckPage.js
Labels: For: Deploy, Type: Refactor

#44 🛠️ : CheckPage 티켓 처리시 사운드 발생
  package-lock.json
  public/errorSound.mp3
  public/successSound.mp3
  src/components/Tickets/CheckPage/CheckPage.js
  src/state/actions-creators/CheckPage.js
Labels: Type: Feature

#46 [소켓] 모든 창에서 입장 알림 띄우기
  src/App.js
  src/components/Tickets/EnterPage/EnterList.js
  src/components/Tickets/EnterPage/EnterPage.js
  src/components/Tickets/EnterPage/RecentEnter.js
  src/components/Tickets/EnterPage/SocketConnect.js
  src/contexts/socketContext.js
  src/contexts/socketProvider.js
  src/index.js
Labels: For: Views, For: Markup/UX, Type: Feature

#47 [v0.1.6] 체크시 소리 , 다른페이지에서도 소켓 이벤트 수신
  package-lock.json
  public/errorSound.mp3
  public/successSound.mp3
  src/App.js
  src/components/Tickets/CheckPage/CheckPage.js
  src/components/Tickets/EnterPage/EnterList.js
  src/components/Tickets/EnterPage/EnterPage.js
  src/components/Tickets/EnterPage/RecentEnter.js
  src/components/Tickets/EnterPage/SocketConnect.js
  src/contexts/socketContext.js
  src/contexts/socketProvider.js
  src/index.js
  src/state/actions-creators/CheckPage.js
Labels: For: API, For: Deploy, Type: Feature

#49 Feature/OrdersPage, CheckPage
  public/errorSound.mp3
  public/qrSound.mp3
  public/successSound.mp3
  src/components/AuthPage/LoginPage.js
  src/components/LandingPage/LandingPage.js
  src/components/MainLayout/MainLayout.js
  src/components/Tables/OrdersPage/OrdersPage.js
  src/components/Tables/TicketsPage/TicketsPage.js
  src/components/Tables/UsersPage/Table.js
  src/components/Tickets/CheckPage/CheckPage.js
  src/contexts/socketProvider.js
  src/hoc/AuthPass.js
  src/hoc/requireAuth.js
  src/state/actions-creators/CheckPage.js
  src/state/actions-creators/LandingPage.js
  src/state/actions-creators/enterPage.js
  src/state/actions-creators/examplePagination.js
  src/state/actions-creators/logout.js
  src/state/actions-creators/orderListPagination.js
  src/state/actions-creators/randomCom.js
  src/state/actions-creators/slackMessage.js
  src/state/actions-creators/slackValidation.js
  src/state/actions-creators/ticketPagination.js
  src/state/actions-creators/userLookup.js
  src/state/actions-creators/usersPage.js
  src/state/reducers/examplePagination.js
  src/state/reducers/ticketPagination.js
  src/state/storeSetting.js
Labels: Type: Feature, Type: Refactor

#50 [파비콘] 파비콘, 콘텐트 수정
  public/favicon.ico
  public/index.html
  src/components/Tables/TicketsPage/TicketsPage.js
  src/state/actions-creators/ticketPagination.js
  src/state/reducers/ticketPagination.js
Labels: For: Views, Type: Refactor

#51 [v1.0.0] 프로덕션 최종 수정
  public/errorSound.mp3
  public/favicon.ico
  public/index.html
  public/notificationSound.mp3
  public/qrSound.mp3
  public/successSound.mp3
  src/components/AuthPage/LoginPage.js
  src/components/LandingPage/LandingPage.js
  src/components/MainLayout/MainLayout.js
  src/components/Tables/OrdersPage/OrdersPage.js
  src/components/Tables/TicketsPage/TicketsPage.js
  src/components/Tables/UsersPage/Table.js
  src/components/Tickets/CheckPage/CheckPage.js
  src/contexts/socketProvider.js
  src/hoc/AuthPass.js
  src/hoc/requireAuth.js
  src/state/actions-creators/CheckPage.js
  src/state/actions-creators/LandingPage.js
  src/state/actions-creators/enterPage.js
  src/state/actions-creators/examplePagination.js
  src/state/actions-creators/logout.js
  src/state/actions-creators/orderListPagination.js
  src/state/actions-creators/randomCom.js
  src/state/actions-creators/slackMessage.js
  src/state/actions-creators/slackValidation.js
  src/state/actions-creators/ticketPagination.js
  src/state/actions-creators/userLookup.js
  src/state/actions-creators/usersPage.js
  src/state/reducers/examplePagination.js
  src/state/reducers/ticketPagination.js
  src/state/storeSetting.js
Labels: For: Deploy, For: Views, For: Markup/UX, Type: Feature, Type: Refactor

#53 [v1.0.1] 티켓 수정시 오류 해결
  src/components/Tables/TicketsPage/TicketsPage.js
  src/state/actions-creators/ticketPagination.js
Labels: For: Deploy, Type: Refactor

#54 [v1.0.2] 로그인 만료 관련 오류 수정
  README.md
  src/config/axiosInstance.js
Labels: For: Deploy, For: Views, Type: Refactor
